[package]
name = "fastxslt"
description = "A Rust-native XSLT engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[features]
allocation-observation = ["dep:allocation-counter"]
workbench = ["dep:iri-string", "dep:quick-xml"]

[dependencies]
allocation-counter = { version = "=0.8.1", optional = true }
iri-string = { version = "=0.7.14", optional = true }
quick-xml = { version = "=0.40.1", optional = true }

[dev-dependencies]
iri-string = "=0.7.14"
quick-xml = "=0.40.1"
serde = { version = "=1.0.229", features = ["derive"] }
toml = "=0.8.23"
